### ISSUE TITLE
make bad vectors

### ISSUE THREAD

**Issue by cryptix** [ssb-ngi-pointer/bendy-butt-spec#10]
We only have a happy path vector file. To make it easier for implementations to harden their verification rules we should also make some with broken/invalid messages.

These might include:

* [x] invalid author formatting
* [x] invalid previous formatting (type, length, ...)
* [x] wrong previous hashes
* [x] broken signature(s)
* [x] wrong sequence numbers
* [x] too long messages
* [x] given that this format is supposed to be just for _metafeed_ managment, broken content

I'd also wager it's better to have these as a seperate file to keep the "good" vector file less complicated.

**Comment by arj03** [comment]
Looks like a good list. Maybe also add message length. And I agree that it would be good with a separate file :)

**Comment by mycognosist** [comment]
> To make it easier for implementations to harden their verification rules we should also make some with broken/invalid messages

Very good idea. Agree with @arj03 on the message length suggestion. Maybe also some incorrect `content` examples, assuming you wish to include broken content validation and not just message validation? So that might include incorrect type for `content` (maybe a string instead of the expected array of dictionary), unsupported `type` value (`metafeed/anomaly`), `nonce` not `base64` encoded etc.
